
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

"$schema" = 'https://starship.rs/config-schema.json'

[fill]
symbol = " "

[directory]
style = "blue bold"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"


[git_status]
format = '([\[$untracked$modified$staged$ahead_behind\]]($style) )'
ahead = '⇡\(${count}\)'
staged = '[+](green)'
untracked = '[?](red)'
modified = '[!](red)'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣\(${count}\)'
style = "cyan"


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"


[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"



[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true



[nodejs]
disabled = true

